### PR TITLE
Sync Builder.sh file with the one from github-config 

### PR DESCRIPTION
**Pull request by pacostas**
## Summary

This PR syncs `.util/builder.sh` file with the one from github-config https://github.com/paketo-buildpacks/github-config/blob/main/implementation/scripts/.util/builders.sh 

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by pacostas** [comment]
For this PR to pass, we need to cut a new release as the https://github.com/paketo-community/ubi-nodejs-extension/pull/82#event-11833434463 has now been merged.

**Comment by pacostas** [comment]
@thitch97 Can you re-run the tests, I guess now they should pass

**Comment by pacostas** [comment]
The tests fail as despite we have a new release on this repo, is not published on dockerhub due to https://github.com/paketo-community/ubi-nodejs-extension/issues/93

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
